# Generated by Django 4.0.4 on 2022-06-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='label',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text',
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
